port:  5000
markdown: kramdown
title: "Chicago Police Misconduct Reports"
name: "Chicago Police Misconduct Reports"
author: "Invisible Institute"
url: http://intro.cpdb.co
encoding: utf-8
timezone: America/Chicago
description: ""
shortdesc: ""
gems:
  - jekyll-redirect-from